[package]
name = "henosis-controller-cloudflare"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
futures.workspace = true
henosis-controller-runtime.workspace = true
henosis-types.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
tokio.workspace = true
uuid.workspace = true

[lints]
workspace = true
