[package]
name = "henosis-multi-stream-merge"
version = "0.0.0"
description = "Standalone ordered virtual stream over many append-only streams"
repository.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
faultline.workspace = true
futures.workspace = true
henosis-storage.workspace = true
workspace-hack = { version = "0.0.0", path = "../workspace-hack" }
