[package]
name = "henosis-db-model"
version = "0.0.0"
description = "Diesel models for Henosis PostgreSQL metadata"
repository.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
diesel.workspace = true
henosis-db-schema.workspace = true
workspace-hack = { version = "0.0.0", path = "../workspace-hack" }

[lints]
workspace = true
