[package]
name = "henosis-types"
version = "0.0.0"
description = "Domain types and controller/evaluation seams for Henosis"
repository.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
blake3.workspace = true
futures.workspace = true
hex.workspace = true
iddqd.workspace = true
newtype-uuid.workspace = true
ryu-js.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
uuid.workspace = true
workspace-hack = { version = "0.0.0", path = "../workspace-hack" }
