[package]
name = "workspace-hack"
version = "0.0.0"
repository.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
description = "workspace-hack package, managed by hakari"

### BEGIN HAKARI SECTION
[dependencies]
bytes = { version = "1", features = ["serde"] }
diesel = { version = "2", default-features = false, features = ["i-implement-a-third-party-backend-and-opt-into-breaking-changes", "postgres", "uuid"] }
either = { version = "1", features = ["serde", "use_std"] }
futures-channel = { version = "0.3", features = ["sink"] }
futures-task = { version = "0.3", default-features = false, features = ["std"] }
futures-util = { version = "0.3", features = ["channel", "io", "sink"] }
log = { version = "0.4", default-features = false, features = ["std"] }
serde = { version = "1", features = ["alloc", "derive"] }
serde_core = { version = "1", default-features = false, features = ["alloc", "result", "std"] }
serde_json = { version = "1", features = ["alloc"] }
slab = { version = "0.4" }
smallvec = { version = "1", default-features = false, features = ["const_new"] }
tokio = { version = "1", features = ["io-util", "macros", "net", "parking_lot", "rt-multi-thread", "signal", "sync", "time"] }
tokio-util = { version = "0.7", features = ["codec", "io", "rt"] }
tracing = { version = "0.1" }
tracing-core = { version = "0.1" }
uuid = { version = "1", features = ["fast-rng", "serde", "v4", "v7"] }

[build-dependencies]
darling = { version = "0.21" }
darling_core = { version = "0.21", default-features = false, features = ["suggestions"] }
either = { version = "1", features = ["serde", "use_std"] }
serde = { version = "1", features = ["alloc", "derive"] }
serde_core = { version = "1", default-features = false, features = ["alloc", "result", "std"] }
syn = { version = "2", features = ["extra-traits", "fold", "full", "visit", "visit-mut"] }

[target.x86_64-unknown-linux-gnu.dependencies]
getrandom = { version = "0.4", default-features = false, features = ["std", "sys_rng"] }
libc = { version = "0.2" }

[target.x86_64-unknown-linux-gnu.build-dependencies]
libc = { version = "0.2" }

[target.x86_64-unknown-linux-musl.dependencies]
getrandom = { version = "0.4", default-features = false, features = ["std", "sys_rng"] }
libc = { version = "0.2" }

[target.x86_64-unknown-linux-musl.build-dependencies]
libc = { version = "0.2" }

[target.aarch64-unknown-linux-gnu.dependencies]
getrandom = { version = "0.4", default-features = false, features = ["std", "sys_rng"] }
libc = { version = "0.2" }

[target.aarch64-unknown-linux-gnu.build-dependencies]
libc = { version = "0.2" }

[target.aarch64-unknown-linux-musl.dependencies]
getrandom = { version = "0.4", default-features = false, features = ["std", "sys_rng"] }
libc = { version = "0.2" }

[target.aarch64-unknown-linux-musl.build-dependencies]
libc = { version = "0.2" }

[target.aarch64-apple-darwin.dependencies]
bitflags = { version = "2", default-features = false, features = ["std"] }
getrandom = { version = "0.4", default-features = false, features = ["std", "sys_rng"] }
libc = { version = "0.2" }

[target.aarch64-apple-darwin.build-dependencies]
libc = { version = "0.2" }

### END HAKARI SECTION

[lints]
workspace = true
