[package]
name = "henosis-proto"
version = "0.0.0"
description = "Generated Henosis ConnectRPC protocol bindings"
repository.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
blake3.workspace = true
buffa.workspace = true
buffa-types.workspace = true
connectrpc.workspace = true
futures.workspace = true
henosis-types.workspace = true
newtype-uuid.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
workspace-hack = { version = "0.0.0", path = "../workspace-hack" }

[lints]
workspace = true
