[package]
name = "henosis-proto"
version = "0.0.0"
description = "Generated Henosis ConnectRPC protocol bindings"
repository.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
buffa.workspace = true
connectrpc.workspace = true
serde.workspace = true
workspace-hack = { version = "0.0.0", path = "../workspace-hack" }
