name: Template Update
permissions:
  contents: read
on:
  schedule:
    - cron: '1 1 1 * *'
  workflow_dispatch:
env:
  TEMPLATE_REPO: "skuld-systems/_rust"
  TEMPLATE_BRANCH: "main"
concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true
jobs:
  update:
    name: Update
    if: github.repository != 'skuld-systems/_rust'
    permissions:
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0
          persist-credentials: true # to push the branch and create PR
      - name: Checkout template
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          repository: ${{ env.TEMPLATE_REPO }}
          ref: ${{ env.TEMPLATE_BRANCH }}
          path: .template
          fetch-depth: 0
          persist-credentials: false
      - name: Configure git
        run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email '<>'
      - name: Merge template
        run: |
          git remote add template ./.template
          git fetch template "${TEMPLATE_BRANCH}"
          git checkout -b template-update
          git merge "template/${TEMPLATE_BRANCH}" -m 'chore: Update from template'
          git remote remove template
          rm -rf .template
      - name: Clear any existing branch
        run: "git push origin --delete template-update"
        continue-on-error: true
      - name: Push branch
        run: "git push --set-upstream origin template-update"
      - name: Create PR
        run: "gh pr create --head template-update --title 'chore: Update from template' --body ''"
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Merge PR
        run: "gh pr merge --auto --delete-branch"
        env:
          GH_TOKEN: ${{ github.token }}
